version: '3.7'

services:
  interface:
    build: 
      context: ./interface/Iot-system
    container_name: interface
    networks:
      - iot-system-network
    environment:
      - IP_API_BROKER=192.168.0.115:8082
    ports:
      - "3000:3000"
  server:
    build:
      context: ./server-broker
    container_name: server
    stdin_open: true
    tty: true
    networks:
      - iot-system-network
    ports:
      - "8080:8080"
      - "8081:8081/udp"
      - "8082:8082"
  sensor:
    build:
      context: ./devices/sensor
    container_name: temperature_sensor
    environment:
      - IP_BROKER=server
    stdin_open: true
    tty: true
    networks:
      - iot-system-network
  tv:
    build:
      context: ./devices/tv
    container_name: television
    environment:
      - IP_BROKER=server
    stdin_open: true
    tty: true
    networks:
      - iot-system-network
networks:
  iot-system-network:
    driver: bridge
