version: '3.7'

services:
  client:
    build: 
      context: ./interface/Iot-system
    networks:
      - iot-system-network
    environment:
      - IP_API_BROKER=192.168.0.115:8082
    ports:
      - "3000:3000"
  server:
    build:
      context: ./server-broker
    stdin_open: true
    tty: true
    hostname: broker
    networks:
      - iot-system-network
    ports:
      - "8080:8080"
      - "8081:8081/udp"
      - "8082:8082"
  device:
    build:
      context: ./devices
    environment:
      - IP_BROKER=192.168.0.115
    stdin_open: true
    tty: true
    networks:
      - iot-system-network
networks:
  iot-system-network:
    driver: bridge