# Use a imagem oficial do Python
FROM python:3.9-slim

COPY . ./app
# Defina o diretório de trabalho
WORKDIR /app



# Copie o código-fonte para o diretório de trabalho


# Comando para iniciar o aplicativo
CMD ["python", "tempSensor.py"]